T = 10e-6;
B = 30e6;
K = B / T;
Fs = 10 * B;
Ts = 1 / Fs;
N = T / Ts;
t = linspace(-T / 2, T / 2, N);
St = exp(j * pi * K * t.^2);
Ht = exp(-j * pi * K * t.^2);
Sot = conv(St, Ht);
subplot(211)
L = 2 * N - 1;
t1 = linspace(-T, T, L);
Z = abs(Sot);
Z = Z / max(Z);
Z1 = abs(sinc(B.*t1));
Z1 = 20 * log10(Z1 + 1e-6);
t1 = t1 * B;
plot(t1, Z, t1, Z1, 'r.');
axis([-15, 15, -50, inf]);
grid on;
legend('仿真', 'sinc');
xlabel('t');
ylabel('振幅/dB');
title('匹配滤波器后的线性调频信号');
subplot(212);
N0 = 3 * Fs / B;
t2 = -N0 * Ts : Ts : N0 * Ts;
t2 = B * t2;
plot(t2, Z(N - N0 : N + N0), t2, Z1(N - N0 : N + N0), 'r.');
axis([-inf, inf, -50, inf]);
grid on;
axis tight;
set(gca, 'Ytick', [-13.4, -4, 0], 'Xtick', [-3, -2, -1, -0.5, 0, 0.5, 1, 2, 3]);
xlabel('t');
ylabel('振幅/dB');
title('放大后匹配滤波器的线性调频信号');
axis tight;