T = 10e-6;
B = 30e6;
K = B / T;
F = 10 * B;
Ts_temp = 1 / F;
N = T / Ts_temp;
t = linspace(-T / 2, T / 2, N);
S_temp = exp(j * pi * K * t.^2);
H_temp = exp(-j * pi * K * t.^2);
Sot = conv(S_temp, H_temp);
subplot(211)
L = 2 * N - 1;
T_temp = linspace(-T, T, L);
Z = abs(Sot);
Z = Z / max(Z);
Z = 20 * log10(Z + 1e-6);
Z_temp = abs(sinc(B.*T_temp));
Z_temp = 20 * log10(Z_temp + 1e-6);
T_temp = T_temp * B;
plot(T_temp, Z, T_temp, Z_temp, 'r.');
axis([-15, 15, -50, inf]);
grid on;
legend('仿真', 'sinc');
xlabel('t');
ylabel('振幅/dB');
title('匹配滤波器后的线性调频信号');
subplot(212);
N0 = 3 * F / B;
t2 = -N0 * Ts_temp : Ts_temp : N0 * Ts_temp;
t2 = B * t2;
plot(t2, Z(N - N0 : N + N0), t2, Z_temp(N - N0 : N + N0), 'r.');
axis([-inf, inf, -50, inf]);
grid on;
axis tigH_temp;
set(gca, 'Ytick', [-13.4, -4, 0], 'Xtick', [-3, -2, -1, -0.5, 0, 0.5, 1, 2, 3]);
xlabel('t');
ylabel('振幅/dB');
title('放大后匹配滤波器的线性调频信号');
axis tigH_temp;